-- GENERATED by scripts/test/prepare-db-access-tests.py from client_grant_audit_test.sql.in - do not edit.
-- Exercise the standing client-grant audit against the real schema, then prove
-- each check detects the shape it exists for and ignores the shapes it must not.
begin;
select plan(10);

create temporary table grant_snapshot as
-- Client-grant audit for schema `public`. Run it against the project and read
-- the `finding` column: HEALTHY means that check passed. Any other value names
-- the object to investigate. Both checks here are exact catalog facts rather
-- than heuristics, so neither needs human judgement to interpret.
--
-- This is the companion to identity_disclosure_audit.sql, which asks who can
-- READ identity. This one asks a narrower question that the other deliberately
-- does not: which client roles can WRITE, and whether anything but a policy is
-- stopping them.
--
-- It exists because of the recurrence tracked in #547. `20251023000014_grants.sql`
-- sets `ALTER DEFAULT PRIVILEGES ... GRANT ALL ON TABLES TO anon, authenticated`,
-- so every table created after it inherits client grants. Three tables then
-- shipped with a permissive write policy on top of that inherited grant:
-- plugin_downloads (#488), completed_authentications (#536) and the pair
-- secret_access_log / plugin_api_key_logs (#538). Each was found by a person
-- reading a migration, three separate times.
--
-- 20260908000000_explicit_anon_grants.sql closed the `anon` half of the
-- inheritance for objects created after it. It deliberately left `authenticated`
-- alone, because for tables RLS is the intended gate. That is a reasonable
-- decision, and it is exactly why these two checks are worth having: once RLS is
-- the only thing standing in front of a client role, "RLS is enabled" and "the
-- policy is not a rubber stamp" stop being style points and become the control.
--
-- Run it after any migration that creates a table or a policy.

-- ---------------------------------------------------------------------------
-- CHECK G1: no table reachable by a client role is missing RLS.
--
-- Without RLS the table privilege IS the access decision, and the inherited
-- default grant hands that privilege out silently. CHECK 3b in the identity
-- audit asks a similar question, but only of tables carrying an `email`,
-- `display_name` or `full_name` column, and only as an advisory. Two of the
-- three recurrences above carry no such column, so that filter would have
-- skipped them both.
--
-- No column filter and no allowlist here. Every one of the 34 tables in `public`
-- enables RLS today, so an empty exception list is the accurate description of
-- the schema rather than an aspiration, and a new table without RLS is a mistake
-- until someone argues otherwise in review.
-- ---------------------------------------------------------------------------
select 'CHECK G1: client-reachable table without RLS' as "check",
       coalesce(
         nullif(string_agg(distinct c.oid::regclass::text, ', ' order by c.oid::regclass::text), ''),
         'HEALTHY'
       ) as finding
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relkind in ('r', 'p')
  and not c.relrowsecurity
  and exists (
    select 1
    -- Cast to `name` explicitly. Both has_table_privilege overloads take a role
    -- as `name` or as `oid`, and an uncast text variable leaves the choice to
    -- type resolution rather than stating it.
    from unnest(array['anon', 'authenticated']::name[]) as client(role_name)
    where has_table_privilege(client.role_name, c.oid, 'SELECT')
       or has_table_privilege(client.role_name, c.oid, 'INSERT')
       or has_table_privilege(client.role_name, c.oid, 'UPDATE')
       or has_table_privilege(client.role_name, c.oid, 'DELETE')
  )

union all

-- ---------------------------------------------------------------------------
-- CHECK G2: no write policy reachable by a client role is a rubber stamp.
--
-- A policy whose predicate is the literal `true` adds no restriction. On SELECT
-- that is sometimes intended, and the identity audit's CHECK 3 already covers
-- the identity-bearing case. On INSERT, UPDATE or DELETE it means any caller
-- holding the role may write any row, which is what produced all three
-- recurrences above.
--
-- The discriminating signal is the predicate, NOT a missing `TO` clause. A
-- policy with no `TO` applies to PUBLIC, which is how all three slipped past
-- review, but 101 of the 128 policies written in this schema omit `TO`. Gating
-- on that alone would report most of the schema and be switched off within a
-- week. Taken together, "write" plus "client role" plus "literally true" matches
-- two policies in the whole schema and nothing else.
--
-- `qual` is the USING predicate and `with_check` the WITH CHECK predicate.
-- INSERT policies carry only the latter, DELETE only the former, and UPDATE or
-- ALL may carry both. A permissive WITH CHECK on an otherwise scoped UPDATE
-- still lets a caller rewrite a row it owns into any shape, so either predicate
-- being `true` is enough to report. service_role is not a client role and is
-- excluded by the role filter, so a deliberate `TO service_role WITH CHECK
-- (true)` writer policy is correctly silent here.
-- ---------------------------------------------------------------------------
select 'CHECK G2: permissive write policy for a client role' as "check",
       coalesce(
         nullif(string_agg(distinct pol.tablename || '.' || pol.policyname, ', '
                           order by pol.tablename || '.' || pol.policyname), ''),
         'HEALTHY'
       ) as finding
from pg_policies pol
where pol.schemaname = 'public'
  and pol.cmd in ('INSERT', 'UPDATE', 'DELETE', 'ALL')
  and pol.roles && array['anon', 'authenticated', 'public']::name[]
  and (
    btrim(lower(coalesce(pol.qual, ''))) in ('true', '(true)')
    or btrim(lower(coalesce(pol.with_check, ''))) in ('true', '(true)')
  );


-- ---------------------------------------------------------------------------
-- Gates on the live schema.
-- ---------------------------------------------------------------------------
select is(finding, 'HEALTHY', "check") from grant_snapshot
where "check" = 'CHECK G1: client-reachable table without RLS';

-- G2 is asserted as a subset rather than as HEALTHY, on purpose. The two
-- policies named below are the open bug that #538 removes, and they are still
-- on `dev` at the time of writing. Writing `is(finding, 'HEALTHY')` here would
-- fail today; writing `is(finding, '<those two>')` would pass today and then
-- fail the moment #538 merged, which is a landmine for whoever merges it. The
-- subtraction below passes in both states and still fails on anything NEW, so
-- it gates the regression without encoding the bug's lifetime. When #538 lands,
-- the array can be emptied and this becomes a plain HEALTHY assertion.
select is(
  (select coalesce(
            nullif(
              array_to_string(
                array(
                  select unnest(string_to_array(finding, ', '))
                  except
                  select unnest(array[
                    'plugin_api_key_logs.Service role can insert API key logs',
                    'secret_access_log.secret_access_log_insert'
                  ])
                ), ', '),
              ''),
            'HEALTHY')
   from grant_snapshot
   where "check" = 'CHECK G2: permissive write policy for a client role'),
  'HEALTHY',
  'no permissive client write policy beyond the two #538 removes'
);

-- ---------------------------------------------------------------------------
-- Detection fixtures. A check that never fires proves nothing, so each check is
-- shown naming a planted violation and staying silent on its near misses.
-- ---------------------------------------------------------------------------

-- G1: granted to a client role, no RLS. The violation.
create table public.pgtap_grant_no_rls(id int);
grant select on public.pgtap_grant_no_rls to authenticated;

-- G1 near miss: same grant, RLS on.
create table public.pgtap_grant_with_rls(id int);
alter table public.pgtap_grant_with_rls enable row level security;
grant select on public.pgtap_grant_with_rls to authenticated;

-- G1 near miss: no RLS, but no client role can reach it either.
create table public.pgtap_grant_unreachable(id int);
revoke all on public.pgtap_grant_unreachable from anon, authenticated;

-- G2: permissive INSERT with no TO clause, which is the shape that applies to
-- PUBLIC and produced all three recurrences.
create table public.pgtap_policy_open_insert(id int);
alter table public.pgtap_policy_open_insert enable row level security;
grant insert on public.pgtap_policy_open_insert to authenticated;
create policy pgtap_open_insert on public.pgtap_policy_open_insert
  for insert with check (true);

-- G2: scoped USING, permissive WITH CHECK on UPDATE. Reachable row, any shape.
create table public.pgtap_policy_open_update(id int, owner uuid);
alter table public.pgtap_policy_open_update enable row level security;
grant update on public.pgtap_policy_open_update to authenticated;
create policy pgtap_open_update on public.pgtap_policy_open_update
  for update to authenticated using (owner = auth.uid()) with check (true);

-- G2 near miss: permissive, but the grantee is not a client role. This is
-- exactly #538's replacement policy and it must stay silent.
create table public.pgtap_policy_service_role(id int);
alter table public.pgtap_policy_service_role enable row level security;
create policy pgtap_service_write on public.pgtap_policy_service_role
  for insert to service_role with check (true);

-- G2 near miss: permissive SELECT. Read exposure is CHECK 3's question.
create table public.pgtap_policy_open_select(id int);
alter table public.pgtap_policy_open_select enable row level security;
grant select on public.pgtap_policy_open_select to authenticated;
create policy pgtap_open_select on public.pgtap_policy_open_select
  for select to authenticated using (true);

-- G2 near miss: a write policy that actually restricts.
create table public.pgtap_policy_scoped_write(id int, owner uuid);
alter table public.pgtap_policy_scoped_write enable row level security;
grant insert on public.pgtap_policy_scoped_write to authenticated;
create policy pgtap_scoped_write on public.pgtap_policy_scoped_write
  for insert to authenticated with check (owner = auth.uid());

create temporary table grant_planted as
-- Client-grant audit for schema `public`. Run it against the project and read
-- the `finding` column: HEALTHY means that check passed. Any other value names
-- the object to investigate. Both checks here are exact catalog facts rather
-- than heuristics, so neither needs human judgement to interpret.
--
-- This is the companion to identity_disclosure_audit.sql, which asks who can
-- READ identity. This one asks a narrower question that the other deliberately
-- does not: which client roles can WRITE, and whether anything but a policy is
-- stopping them.
--
-- It exists because of the recurrence tracked in #547. `20251023000014_grants.sql`
-- sets `ALTER DEFAULT PRIVILEGES ... GRANT ALL ON TABLES TO anon, authenticated`,
-- so every table created after it inherits client grants. Three tables then
-- shipped with a permissive write policy on top of that inherited grant:
-- plugin_downloads (#488), completed_authentications (#536) and the pair
-- secret_access_log / plugin_api_key_logs (#538). Each was found by a person
-- reading a migration, three separate times.
--
-- 20260908000000_explicit_anon_grants.sql closed the `anon` half of the
-- inheritance for objects created after it. It deliberately left `authenticated`
-- alone, because for tables RLS is the intended gate. That is a reasonable
-- decision, and it is exactly why these two checks are worth having: once RLS is
-- the only thing standing in front of a client role, "RLS is enabled" and "the
-- policy is not a rubber stamp" stop being style points and become the control.
--
-- Run it after any migration that creates a table or a policy.

-- ---------------------------------------------------------------------------
-- CHECK G1: no table reachable by a client role is missing RLS.
--
-- Without RLS the table privilege IS the access decision, and the inherited
-- default grant hands that privilege out silently. CHECK 3b in the identity
-- audit asks a similar question, but only of tables carrying an `email`,
-- `display_name` or `full_name` column, and only as an advisory. Two of the
-- three recurrences above carry no such column, so that filter would have
-- skipped them both.
--
-- No column filter and no allowlist here. Every one of the 34 tables in `public`
-- enables RLS today, so an empty exception list is the accurate description of
-- the schema rather than an aspiration, and a new table without RLS is a mistake
-- until someone argues otherwise in review.
-- ---------------------------------------------------------------------------
select 'CHECK G1: client-reachable table without RLS' as "check",
       coalesce(
         nullif(string_agg(distinct c.oid::regclass::text, ', ' order by c.oid::regclass::text), ''),
         'HEALTHY'
       ) as finding
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relkind in ('r', 'p')
  and not c.relrowsecurity
  and exists (
    select 1
    -- Cast to `name` explicitly. Both has_table_privilege overloads take a role
    -- as `name` or as `oid`, and an uncast text variable leaves the choice to
    -- type resolution rather than stating it.
    from unnest(array['anon', 'authenticated']::name[]) as client(role_name)
    where has_table_privilege(client.role_name, c.oid, 'SELECT')
       or has_table_privilege(client.role_name, c.oid, 'INSERT')
       or has_table_privilege(client.role_name, c.oid, 'UPDATE')
       or has_table_privilege(client.role_name, c.oid, 'DELETE')
  )

union all

-- ---------------------------------------------------------------------------
-- CHECK G2: no write policy reachable by a client role is a rubber stamp.
--
-- A policy whose predicate is the literal `true` adds no restriction. On SELECT
-- that is sometimes intended, and the identity audit's CHECK 3 already covers
-- the identity-bearing case. On INSERT, UPDATE or DELETE it means any caller
-- holding the role may write any row, which is what produced all three
-- recurrences above.
--
-- The discriminating signal is the predicate, NOT a missing `TO` clause. A
-- policy with no `TO` applies to PUBLIC, which is how all three slipped past
-- review, but 101 of the 128 policies written in this schema omit `TO`. Gating
-- on that alone would report most of the schema and be switched off within a
-- week. Taken together, "write" plus "client role" plus "literally true" matches
-- two policies in the whole schema and nothing else.
--
-- `qual` is the USING predicate and `with_check` the WITH CHECK predicate.
-- INSERT policies carry only the latter, DELETE only the former, and UPDATE or
-- ALL may carry both. A permissive WITH CHECK on an otherwise scoped UPDATE
-- still lets a caller rewrite a row it owns into any shape, so either predicate
-- being `true` is enough to report. service_role is not a client role and is
-- excluded by the role filter, so a deliberate `TO service_role WITH CHECK
-- (true)` writer policy is correctly silent here.
-- ---------------------------------------------------------------------------
select 'CHECK G2: permissive write policy for a client role' as "check",
       coalesce(
         nullif(string_agg(distinct pol.tablename || '.' || pol.policyname, ', '
                           order by pol.tablename || '.' || pol.policyname), ''),
         'HEALTHY'
       ) as finding
from pg_policies pol
where pol.schemaname = 'public'
  and pol.cmd in ('INSERT', 'UPDATE', 'DELETE', 'ALL')
  and pol.roles && array['anon', 'authenticated', 'public']::name[]
  and (
    btrim(lower(coalesce(pol.qual, ''))) in ('true', '(true)')
    or btrim(lower(coalesce(pol.with_check, ''))) in ('true', '(true)')
  );


select ok(finding like '%pgtap_grant_no_rls%', 'G1 names a client-granted table without RLS')
from grant_planted where "check" = 'CHECK G1: client-reachable table without RLS';
select ok(finding not like '%pgtap_grant_with_rls%', 'G1 ignores the same table once RLS is on')
from grant_planted where "check" = 'CHECK G1: client-reachable table without RLS';
select ok(finding not like '%pgtap_grant_unreachable%', 'G1 ignores a table no client role can reach')
from grant_planted where "check" = 'CHECK G1: client-reachable table without RLS';

select ok(finding like '%pgtap_open_insert%', 'G2 names a permissive INSERT policy with no TO clause')
from grant_planted where "check" = 'CHECK G2: permissive write policy for a client role';
select ok(finding like '%pgtap_open_update%', 'G2 names a permissive WITH CHECK on a scoped UPDATE')
from grant_planted where "check" = 'CHECK G2: permissive write policy for a client role';
select ok(finding not like '%pgtap_service_write%', 'G2 ignores a permissive policy scoped to service_role')
from grant_planted where "check" = 'CHECK G2: permissive write policy for a client role';
select ok(finding not like '%pgtap_open_select%', 'G2 ignores a permissive SELECT policy')
from grant_planted where "check" = 'CHECK G2: permissive write policy for a client role';
select ok(finding not like '%pgtap_scoped_write%', 'G2 ignores a write policy that restricts')
from grant_planted where "check" = 'CHECK G2: permissive write policy for a client role';

select * from finish();
rollback;
